/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import modelo.AdminBD;
import modelo.Alcancia;
import modelo.Propietario;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author Jhon Nash
 */
public class JFrameVentana extends JFrame {
    private Alcancia alcancia;
    private AdminBD adminBD;
    Border border;
    private String auxMoneda;
    
    
    /**
     * Creates new form JFrameVentana
     */
    public JFrameVentana() {
        auxMoneda = null;
        border = LineBorder.createGrayLineBorder();
        adminBD = new AdminBD();
        alcancia = new Alcancia();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonAgregarMoneda = new javax.swing.JButton();
        jlblCentavos = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        jlblDosPesos = new javax.swing.JLabel();
        jlblCincoPesos = new javax.swing.JLabel();
        jlblDiazPesos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCerdo = new javax.swing.JLabel();
        jLabelAgrego = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAgrego = new javax.swing.JTextField();
        jTextFieldContenidoAlcancia = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonMartillo = new javax.swing.JButton();
        jLabelPropietario = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jTextFieldPropietario = new javax.swing.JTextField();
        jTextFieldFecha = new javax.swing.JTextField();
        jButtonNuevaAlcancia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("monedas"));

        jButtonAgregarMoneda.setText("Agregar Moneda");
        jButtonAgregarMoneda.setEnabled(false);
        jButtonAgregarMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarMonedaActionPerformed(evt);
            }
        });

        jlblCentavos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCentavos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moneda-50-centavos-2.png"))); // NOI18N
        jlblCentavos.setText("0");
        jlblCentavos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlblCentavos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlblCentavos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblCentavosMouseClicked(evt);
            }
        });

        lblPeso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mexico-moneda-de-1-peso.jpg"))); // NOI18N
        lblPeso.setText("0");
        lblPeso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPeso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblPeso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPesoMouseClicked(evt);
            }
        });

        jlblDosPesos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblDosPesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2pesos.jpg"))); // NOI18N
        jlblDosPesos.setText("0");
        jlblDosPesos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlblDosPesos.setVerifyInputWhenFocusTarget(false);
        jlblDosPesos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlblDosPesos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblDosPesosMouseClicked(evt);
            }
        });

        jlblCincoPesos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCincoPesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5pesos.png"))); // NOI18N
        jlblCincoPesos.setText("0");
        jlblCincoPesos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlblCincoPesos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlblCincoPesos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblCincoPesosMouseClicked(evt);
            }
        });

        jlblDiazPesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/10pesos.png"))); // NOI18N
        jlblDiazPesos.setText("0");
        jlblDiazPesos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlblDiazPesos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlblDiazPesos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblDiazPesosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblCentavos, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPeso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblDosPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblCincoPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblDiazPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAgregarMoneda)
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButtonAgregarMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblDiazPesos, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jlblCincoPesos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblDosPesos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblCentavos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Alcancia"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 104, -1, -1));

        jLabelCerdo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerditobn.jpeg"))); // NOI18N
        jPanel2.add(jLabelCerdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabelAgrego.setText("Se agrego:");
        jPanel2.add(jLabelAgrego, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel3.setText("Pesos en Alcancia:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jTextFieldAgrego.setEditable(false);
        jPanel2.add(jTextFieldAgrego, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 220, -1));

        jTextFieldContenidoAlcancia.setEditable(false);
        jPanel2.add(jTextFieldContenidoAlcancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 220, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Romper Alcancia"));

        jButtonMartillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/martillo.jpg"))); // NOI18N
        jButtonMartillo.setEnabled(false);

        jLabelPropietario.setText("Propietario:");

        jLabelFecha.setText("Fecha:");

        jTextFieldPropietario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPropietarioKeyTyped(evt);
            }
        });

        jTextFieldFecha.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMartillo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPropietario)
                            .addComponent(jLabelFecha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPropietario)
                            .addComponent(jTextFieldFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonMartillo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPropietario)
                    .addComponent(jTextFieldPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jButtonNuevaAlcancia.setText("Nueva Alcancia");
        jButtonNuevaAlcancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaAlcanciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonNuevaAlcancia)
                        .addGap(108, 108, 108))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNuevaAlcancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarMonedaActionPerformed
        // TODO add your handling code here:
        modificaNumeroMonedas();
        
        
    }//GEN-LAST:event_jButtonAgregarMonedaActionPerformed

    private void jButtonNuevaAlcanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaAlcanciaActionPerformed
        // TODO add your handling code here:
       habilitaComponentesPantalla();/*comando oficial*/
       //iniciarSesion();/*comando a implantar en regreso con alcancia llena*/
      
        /*guarda en la base de datos*/
        
        
    }//GEN-LAST:event_jButtonNuevaAlcanciaActionPerformed

    private void jTextFieldPropietarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPropietarioKeyTyped
        // TODO add your handling code here:
         int maximoCadena=30;
        if(jTextFieldPropietario.getText().length() >=maximoCadena){
            evt.consume();
            JOptionPane.showMessageDialog(jLabelAgrego, "Solo 30 caracteres "
                    + "aceptados ");   
        }
        
    }//GEN-LAST:event_jTextFieldPropietarioKeyTyped

    private void jlblCentavosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblCentavosMouseClicked
        auxMoneda = "centavos";
        reiniciarMonedas();       
        jlblCentavos.setBorder(border);   
    }//GEN-LAST:event_jlblCentavosMouseClicked

    private void lblPesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPesoMouseClicked
        auxMoneda = "peso";
        reiniciarMonedas();       
        lblPeso.setBorder(border);
    }//GEN-LAST:event_lblPesoMouseClicked

    private void jlblDosPesosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblDosPesosMouseClicked
        // TODO add your handling code here:
        auxMoneda = "2Pesos";
        reiniciarMonedas();        
        jlblDosPesos.setBorder(border);
    }//GEN-LAST:event_jlblDosPesosMouseClicked

    private void jlblCincoPesosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblCincoPesosMouseClicked
        // TODO add your handling code here:
        auxMoneda = "5Pesos";
        reiniciarMonedas();
        jlblCincoPesos.setBorder(border);

    }//GEN-LAST:event_jlblCincoPesosMouseClicked

    private void jlblDiazPesosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblDiazPesosMouseClicked
        // TODO add your handling code here:
        auxMoneda = "10Pesos";
        reiniciarMonedas();
        jlblDiazPesos.setBorder(border);

    }//GEN-LAST:event_jlblDiazPesosMouseClicked
    public void habilitaComponentesPantalla(){
        String cadena;
        Propietario propietario = new Propietario();
        if(jTextFieldPropietario.getText().isEmpty()){
             JOptionPane.showMessageDialog(jLabelAgrego, "El campo "
                     + "propietario esta vacio, escribe tu nombre completo,"
                     + " gracias");
        }else{
            this.jButtonAgregarMoneda.setEnabled(true);
            this.jButtonMartillo.setEnabled(true);
            this.jButtonNuevaAlcancia.setEnabled(false);
            this.jTextFieldPropietario.setEditable(false);
            //alcancia.setFecha();
            cadena = this.alcancia.getCalendario();
            this.jTextFieldFecha.setText(cadena);
            this.alcancia.setFecha(cadena);
            propietario.setNombre(this.jTextFieldPropietario.getText());
            this.alcancia.setPropietario(propietario);
            adminBD.insertaAlcancia(this.alcancia);
        }
       
    }
    
    public void modificaNumeroMonedas(){
        int valor;
        if(auxMoneda.equals("centavos")){
            valor =dameValorEntero(this.jlblCentavos);
            this.jlblCentavos.setText(""+valor);
            alcancia.setNumCetavo(1);
            this.jTextFieldAgrego.setText("50 Centavos");
            
        }
        if(auxMoneda.equals("peso")){
            valor =dameValorEntero(this.lblPeso);
            this.lblPeso.setText(""+valor);
            alcancia.setNumPeso(1);
            this.jTextFieldAgrego.setText("1 Peso");
            
        }
        if(auxMoneda.equals("2Pesos")){
            valor =dameValorEntero(this.jlblDosPesos);
            this.jlblDosPesos.setText(""+valor);
            alcancia.setNumDosPeos(1);
            this.jTextFieldAgrego.setText("2 Pesos");
        }
        if(auxMoneda.equals("5Pesos")){
            valor =dameValorEntero(this.jlblCincoPesos);
            this.jlblCincoPesos.setText(""+valor);
            alcancia.setNumCincoPesos(1);
            this.jTextFieldAgrego.setText("5 Pesos");
        }
        if(auxMoneda.equals("10Pesos")){
            valor =dameValorEntero(this.jlblDiazPesos);
            this.jlblDiazPesos.setText(""+valor);
            alcancia.setNumDiezPesos(1);
            this.jTextFieldAgrego.setText("10 Pesos");
        }
        
        this.jTextFieldContenidoAlcancia.setText(""+alcancia.calculaTotal());
        adminBD.actualizaAlcancia(alcancia);
        
    }
    
    public int dameValorEntero(JLabel label){
        int valor=0;
        String cadena;
        cadena = label.getText();
        valor= Integer.parseInt(cadena);
        valor = valor + 1;
        
        return valor;
        
        
    }
    
    public void reiniciarMonedas(){
        jlblCentavos.setBorder(null);
        lblPeso.setBorder(null);
        jlblDosPesos.setBorder(null);
        jlblCincoPesos.setBorder(null);
        jlblDiazPesos.setBorder(null);
    }
    
    public void iniciarSesion(){
        this.jButtonAgregarMoneda.setEnabled(true);
        this.jButtonMartillo.setEnabled(true);
        this.jButtonNuevaAlcancia.setEnabled(false);
        this.jTextFieldPropietario.setEditable(false);
            
/*
        //alcancia.setFecha();
        cadena = this.alcancia.getCalendario();
        this.jTextFieldFecha.setText(cadena);
        this.alcancia.setFecha(cadena);
        propietario.setNombre(this.jTextFieldPropietario.getText());
        this.alcancia.setPropietario(propietario);
*/       
        
    }
    
    
    
    /**/
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarMoneda;
    private javax.swing.JButton jButtonMartillo;
    private javax.swing.JButton jButtonNuevaAlcancia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAgrego;
    private javax.swing.JLabel jLabelCerdo;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelPropietario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldAgrego;
    private javax.swing.JTextField jTextFieldContenidoAlcancia;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldPropietario;
    private javax.swing.JLabel jlblCentavos;
    private javax.swing.JLabel jlblCincoPesos;
    private javax.swing.JLabel jlblDiazPesos;
    private javax.swing.JLabel jlblDosPesos;
    private javax.swing.JLabel lblPeso;
    // End of variables declaration//GEN-END:variables
}
